// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/books": {
            "get": {
                "description": "分页查询所有书籍",
                "produces": [
                    "application/json"
                ],
                "summary": "查询书籍列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码（默认1）",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页条数（默认10）",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.BookListResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "新增一本图书到数据库",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "创建新书籍",
                "parameters": [
                    {
                        "description": "书籍信息",
                        "name": "book",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.CreateBookRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handler.BookResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/books/{id}": {
            "get": {
                "description": "通过ID查询书籍详情",
                "produces": [
                    "application/json"
                ],
                "summary": "查询单本书籍",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "书籍ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.BookResponse"
                        }
                    },
                    "400": {
                        "description": "ID格式错误",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "书籍不存在",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "description": "根据ID更新书籍信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "更新书籍信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "书籍ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新的书籍信息",
                        "name": "book",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.UpdateBookRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "更新成功",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "请求参数错误或ID格式错误",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "书籍不存在",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "根据ID软删除书籍",
                "produces": [
                    "application/json"
                ],
                "summary": "删除书籍",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "书籍ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "删除成功",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "ID格式错误",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "书籍不存在",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.BookListResponse": {
            "type": "object",
            "properties": {
                "list": {
                    "description": "分页数据列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.BookResponse"
                    }
                },
                "total": {
                    "description": "总条数",
                    "type": "integer"
                }
            }
        },
        "handler.BookResponse": {
            "type": "object",
            "properties": {
                "author": {
                    "description": "作者",
                    "type": "string"
                },
                "created_at": {
                    "description": "创建时间",
                    "type": "string"
                },
                "description": {
                    "description": "描述",
                    "type": "string"
                },
                "id": {
                    "description": "主键ID",
                    "type": "integer"
                },
                "price": {
                    "description": "价格",
                    "type": "number"
                },
                "title": {
                    "description": "书名",
                    "type": "string"
                },
                "updated_at": {
                    "description": "更新时间",
                    "type": "string"
                }
            }
        },
        "handler.CreateBookRequest": {
            "type": "object",
            "required": [
                "author",
                "title"
            ],
            "properties": {
                "author": {
                    "description": "作者（必填）",
                    "type": "string"
                },
                "description": {
                    "description": "描述",
                    "type": "string"
                },
                "price": {
                    "description": "价格",
                    "type": "number"
                },
                "title": {
                    "description": "书名（必填）",
                    "type": "string"
                }
            }
        },
        "handler.UpdateBookRequest": {
            "type": "object",
            "properties": {
                "author": {
                    "description": "作者（可选）",
                    "type": "string"
                },
                "description": {
                    "description": "描述（可选）",
                    "type": "string"
                },
                "price": {
                    "description": "价格（可选）",
                    "type": "number"
                },
                "title": {
                    "description": "书名（可选，不填则不更新）",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
