// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/books": {
            "get": {
                "description": "分页查询所有书籍",
                "produces": [
                    "application/json"
                ],
                "summary": "查询书籍列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码（默认1）",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页条数（默认10）",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.BookListResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "新增一本图书到数据库",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "创建新书籍",
                "parameters": [
                    {
                        "description": "书籍信息",
                        "name": "book",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.CreateBookRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handler.BookResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/books/{id}": {
            "get": {
                "description": "通过ID查询书籍详情",
                "produces": [
                    "application/json"
                ],
                "summary": "查询单本书籍",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "书籍ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.BookResponse"
                        }
                    },
                    "400": {
                        "description": "ID格式错误",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "书籍不存在",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "description": "根据ID更新书籍信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "更新书籍信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "书籍ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新的书籍信息",
                        "name": "book",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.UpdateBookRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "更新成功",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "请求参数错误或ID格式错误",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "书籍不存在",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "根据ID软删除书籍",
                "produces": [
                    "application/json"
                ],
                "summary": "删除书籍",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "书籍ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "删除成功",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "ID格式错误",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "书籍不存在",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/roles": {
            "post": {
                "description": "讀取一個角色excel，返回json",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "创建新角色",
                "parameters": [
                    {
                        "type": "file",
                        "description": "要上传的文件",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.COCRoleCard"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.Attributes": {
            "type": "object",
            "properties": {
                "(APP)": {
                    "description": "外貌",
                    "type": "integer"
                },
                "(CON)": {
                    "description": "体质",
                    "type": "integer"
                },
                "(DEX)": {
                    "description": "敏捷",
                    "type": "integer"
                },
                "(EDU)": {
                    "description": "教育",
                    "type": "integer"
                },
                "(INT)": {
                    "description": "智力",
                    "type": "integer"
                },
                "(LUK)": {
                    "description": "幸运",
                    "type": "integer"
                },
                "(POW)": {
                    "description": "意志",
                    "type": "integer"
                },
                "(SIZ)": {
                    "description": "体型",
                    "type": "integer"
                },
                "(STR)": {
                    "description": "力量",
                    "type": "integer"
                },
                "derived": {
                    "description": "派生属性",
                    "allOf": [
                        {
                            "$ref": "#/definitions/handler.DerivedAttributes"
                        }
                    ]
                }
            }
        },
        "handler.BasicInfo": {
            "type": "object",
            "properties": {
                "age": {
                    "description": "年龄",
                    "type": "integer"
                },
                "alignment": {
                    "description": "阵营",
                    "type": "string"
                },
                "appearance": {
                    "description": "外貌描述",
                    "type": "string"
                },
                "avatar_url": {
                    "description": "头像URL",
                    "type": "string"
                },
                "backstory": {
                    "description": "背景故事",
                    "type": "string"
                },
                "gender": {
                    "description": "性别",
                    "type": "string"
                },
                "name": {
                    "description": "角色名",
                    "type": "string"
                },
                "occupation": {
                    "description": "职业",
                    "type": "string"
                },
                "race": {
                    "description": "种族",
                    "type": "string"
                }
            }
        },
        "handler.BookListResponse": {
            "type": "object",
            "properties": {
                "list": {
                    "description": "分页数据列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.BookResponse"
                    }
                },
                "total": {
                    "description": "总条数",
                    "type": "integer"
                }
            }
        },
        "handler.BookResponse": {
            "type": "object",
            "properties": {
                "author": {
                    "description": "作者",
                    "type": "string"
                },
                "created_at": {
                    "description": "创建时间",
                    "type": "string"
                },
                "description": {
                    "description": "描述",
                    "type": "string"
                },
                "id": {
                    "description": "主键ID",
                    "type": "integer"
                },
                "price": {
                    "description": "价格",
                    "type": "number"
                },
                "title": {
                    "description": "书名",
                    "type": "string"
                },
                "updated_at": {
                    "description": "更新时间",
                    "type": "string"
                }
            }
        },
        "handler.COCRoleCard": {
            "type": "object",
            "properties": {
                "attributes": {
                    "description": "属性值",
                    "allOf": [
                        {
                            "$ref": "#/definitions/handler.Attributes"
                        }
                    ]
                },
                "basic_info": {
                    "description": "基本信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/handler.BasicInfo"
                        }
                    ]
                },
                "inventory": {
                    "description": "物品与财富",
                    "allOf": [
                        {
                            "$ref": "#/definitions/handler.Inventory"
                        }
                    ]
                },
                "personal_traits": {
                    "description": "个人特征",
                    "allOf": [
                        {
                            "$ref": "#/definitions/handler.PersonalTraits"
                        }
                    ]
                },
                "skills": {
                    "description": "技能",
                    "allOf": [
                        {
                            "$ref": "#/definitions/handler.Skills"
                        }
                    ]
                },
                "status": {
                    "description": "当前状态",
                    "allOf": [
                        {
                            "$ref": "#/definitions/handler.Status"
                        }
                    ]
                }
            }
        },
        "handler.CreateBookRequest": {
            "type": "object",
            "required": [
                "author",
                "title"
            ],
            "properties": {
                "author": {
                    "description": "作者（必填）",
                    "type": "string"
                },
                "description": {
                    "description": "描述",
                    "type": "string"
                },
                "price": {
                    "description": "价格",
                    "type": "number"
                },
                "title": {
                    "description": "书名（必填）",
                    "type": "string"
                }
            }
        },
        "handler.DerivedAttributes": {
            "type": "object",
            "properties": {
                "(HP)": {
                    "description": "生命值",
                    "type": "integer"
                },
                "(MOV)": {
                    "description": "移动力",
                    "type": "integer"
                },
                "(MP)": {
                    "description": "魔法值",
                    "type": "integer"
                },
                "(SAN)": {
                    "description": "理智值",
                    "type": "integer"
                },
                "actions": {
                    "description": "行动数",
                    "type": "integer"
                },
                "loadlimit(kg)": {
                    "description": "负重上限(kg)",
                    "type": "integer"
                }
            }
        },
        "handler.Equipment": {
            "type": "object",
            "properties": {
                "ammo": {
                    "description": "弹药（仅武器有，可选）",
                    "type": "integer"
                },
                "name": {
                    "description": "装备名称",
                    "type": "string"
                },
                "quantity": {
                    "description": "数量",
                    "type": "integer"
                },
                "remark": {
                    "description": "备注（可选）",
                    "type": "string"
                }
            }
        },
        "handler.Inventory": {
            "type": "object",
            "properties": {
                "equipments": {
                    "description": "装备列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.Equipment"
                    }
                },
                "wealth": {
                    "description": "财富信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/handler.Wealth"
                        }
                    ]
                }
            }
        },
        "handler.PersonalTraits": {
            "type": "object",
            "properties": {
                "importantItem": {
                    "description": "重要物品",
                    "type": "string"
                },
                "importantPerson": {
                    "description": "重要之人",
                    "type": "string"
                },
                "personality": {
                    "description": "个性特点",
                    "type": "string"
                },
                "specialAbility": {
                    "description": "特殊能力",
                    "type": "string"
                }
            }
        },
        "handler.Skill": {
            "type": "object",
            "properties": {
                "name": {
                    "description": "技能名称",
                    "type": "string"
                },
                "remark": {
                    "description": "备注（可选）",
                    "type": "string"
                },
                "value": {
                    "description": "技能数值",
                    "type": "integer"
                }
            }
        },
        "handler.Skills": {
            "type": "object",
            "properties": {
                "general": {
                    "description": "通用技能",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.Skill"
                    }
                },
                "magic": {
                    "description": "魔法技能",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.Skill"
                    }
                },
                "occupational": {
                    "description": "职业技能",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.Skill"
                    }
                }
            }
        },
        "handler.Status": {
            "type": "object",
            "properties": {
                "currentHP": {
                    "description": "当前生命值",
                    "type": "integer"
                },
                "currentSAN": {
                    "description": "当前理智值",
                    "type": "integer"
                },
                "isInjured": {
                    "description": "是否受伤",
                    "type": "boolean"
                },
                "isInsane": {
                    "description": "是否疯狂",
                    "type": "boolean"
                },
                "remark": {
                    "description": "备注",
                    "type": "string"
                }
            }
        },
        "handler.UpdateBookRequest": {
            "type": "object",
            "properties": {
                "author": {
                    "description": "作者（可选）",
                    "type": "string"
                },
                "description": {
                    "description": "描述（可选）",
                    "type": "string"
                },
                "price": {
                    "description": "价格（可选）",
                    "type": "number"
                },
                "title": {
                    "description": "书名（可选，不填则不更新）",
                    "type": "string"
                }
            }
        },
        "handler.Wealth": {
            "type": "object",
            "properties": {
                "assets": {
                    "description": "资产",
                    "type": "string"
                },
                "cash": {
                    "description": "现金",
                    "type": "integer"
                },
                "creditScore": {
                    "description": "信用评级",
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
